### ISSUE TITLE
CRUD Functionality

### ISSUE THREAD

**Issue by henryzhang03** [cse110-sp23-group3/cse110-sp23-group3#26] opened 2023-05-27 20:33 UTC
Use Local storage to save chat sessions, similar to ChatGPT. Implementation can be done in many ways, should just have CRUD. Also make sure there is a unique key for each chat session so that nothing gets overwritten (possibly can ask user to name the session or if they don't want to, default to Session x)

**Comment by phuanh004** [comment] 2023-05-28 10:00
Can you explain in detail what the local storage looks like in "many ways"? (With specific data with {key: value}. So, ppl can vote on which way to go or improve it.

Otherwise, it just the same as #17

**Comment by henryzhang03** [comment] 2023-05-28 23:23
@phuanh004 what I mean is that there are multiple ways in which you can keep the key in the key value pair unique, for example, doing new Date(), or crypto-uuid.

**Comment by phuanh004** [comment] 2023-05-29 01:03
So if that is your thought on #17, please comment there and close this. I don't see anything different. Same title, same topic.

**Comment by phuanh004** [comment] 2023-05-29 04:22
> closed the other issue, no longer a part of milestone 1, and my suggestions can be easily seen here without scrolling much.

This is a weird decision... There are only 3 comments on the old issue. Perhaps contributing to the old issue would be helpful in providing context for others who may not be aware of what's going on. And if the issue is no longer relevant to milestone 1, then moving it to milestone 2 could be a good solution.

**Comment by henryzhang03** [comment] 2023-05-29 05:00
This issue has no milestone, which is intended, it's meant to be between milestone 1 and 2. Regarding the decision, it's not a hard or weird one to make. It's a lot better for a more recent issue to be the one worked on than an old one that people probably won't look at. For context on the issue, there is no need for additional context, as this is a standalone issue and feature as mentioned in the issue title and description. Let's focus on the task at hand rather than getting boggled down by which issues to close.

Anyways, @phuanh004 would you like to create a branch for this?

**Comment by phuanh004** [comment] 2023-05-29 05:15
Alright. What does it mean by being between 2 milestones... If it is in between, then we must decide if we go with that or not... If this will be on the 2nd one, then not yet. 
Since version 1 (or `v1`) of the first milestone is not done yet. The process should be:
1. fix the bugs
2. merge everything to `v1`
3. close the other branches
4. close the 1st milestone
5. Merge to `main`
6. Create a new one for the next version

But make sure we have a clear path with the local storage on how we organize this before having more branches.

**Comment by Christby** [comment] 2023-05-30 04:31
How many people are doing this? I can do issue #24 if you don't need extra help

**Comment by henryzhang03** [comment] 2023-06-04 22:51
As powell mentioned, settings can have CRUD, so for our chat, we can just implement CRD (no update)

**Closed** 2023-06-07 21:51 UTC
Labels: enhancement, help wanted, info-needed
